services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: crm_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dealership_crm
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crm_network
    restart: unless-stopped

  pg_bouncer:
    image: edoburu/pgbouncer:latest
    container_name: crm_pgbouncer
    environment: 
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=123
      - DB_NAME=dealership_crm
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
      - AUTH_TYPE=scram-sha-256
    ports:
     - "6432:6432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 6432 || exit 1"]
      interval: 5s
      timeout: 3s
    depends_on:
      - postgres
    networks:
      - crm_network
    restart: unless-stopped

  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: crm_kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - crm_network
    restart: unless-stopped
  
  ai_agent:
    build:
      context: ./ai_agent
      dockerfile: Dockerfile
    container_name: crm_ai_agent
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:123@postgres:5432/dealership_crm
      - KAFKA_BROKER_URL=kafka:9092
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    volumes:
      - ./mcp_servers:/app/mcp_servers
    depends_on:
      - pg_bouncer
      - kafka
    networks:
      - crm_network
    restart: unless-stopped

  #nginx_gateway:
  #  image: nginx:alpine
  #  container_name: crm_api_gateway
  # ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
  #    - ./api_gateway/ssl:/etc/nginx/ssl:ro
  #  depends_on:
  #    - crm_api
  #    - ai_agent
  #  networks:
  #    - crm_network
  #  restart: unless-stopped
  minio:
    image: minio/minio:latest
    container_name: crm_minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Web Console port
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - crm_network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: crm_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - crm_network
    restart: unless-stopped

volumes:
  pg_data:
  kafka_data:
  minio_data:
  qdrant_data:

networks:
  crm_network: 
    driver: bridge