# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dealership_pb2 as dealership__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dealership_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateToken = channel.unary_unary(
                '/dealership.v1.AuthService/ValidateToken',
                request_serializer=dealership__pb2.TokenRequest.SerializeToString,
                response_deserializer=dealership__pb2.UserProfile.FromString,
                _registered_method=True)
        self.CheckAgentPermissions = channel.unary_unary(
                '/dealership.v1.AuthService/CheckAgentPermissions',
                request_serializer=dealership__pb2.PermissionRequest.SerializeToString,
                response_deserializer=dealership__pb2.PermissionResponse.FromString,
                _registered_method=True)
        self.GetAgentProfile = channel.unary_unary(
                '/dealership.v1.AuthService/GetAgentProfile',
                request_serializer=dealership__pb2.AgentRequest.SerializeToString,
                response_deserializer=dealership__pb2.AgentProfile.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAgentPermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=dealership__pb2.TokenRequest.FromString,
                    response_serializer=dealership__pb2.UserProfile.SerializeToString,
            ),
            'CheckAgentPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAgentPermissions,
                    request_deserializer=dealership__pb2.PermissionRequest.FromString,
                    response_serializer=dealership__pb2.PermissionResponse.SerializeToString,
            ),
            'GetAgentProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentProfile,
                    request_deserializer=dealership__pb2.AgentRequest.FromString,
                    response_serializer=dealership__pb2.AgentProfile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dealership.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dealership.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dealership.v1.AuthService/ValidateToken',
            dealership__pb2.TokenRequest.SerializeToString,
            dealership__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAgentPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dealership.v1.AuthService/CheckAgentPermissions',
            dealership__pb2.PermissionRequest.SerializeToString,
            dealership__pb2.PermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dealership.v1.AuthService/GetAgentProfile',
            dealership__pb2.AgentRequest.SerializeToString,
            dealership__pb2.AgentProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSessionStatus = channel.unary_unary(
                '/dealership.v1.ChatService/GetSessionStatus',
                request_serializer=dealership__pb2.SessionRequest.SerializeToString,
                response_deserializer=dealership__pb2.SessionStatusResponse.FromString,
                _registered_method=True)
        self.SaveHumanMessage = channel.unary_unary(
                '/dealership.v1.ChatService/SaveHumanMessage',
                request_serializer=dealership__pb2.MessageRequest.SerializeToString,
                response_deserializer=dealership__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.UpdateSessionAgent = channel.unary_unary(
                '/dealership.v1.ChatService/UpdateSessionAgent',
                request_serializer=dealership__pb2.ClaimRequest.SerializeToString,
                response_deserializer=dealership__pb2.ClaimResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSessionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveHumanMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSessionAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionStatus,
                    request_deserializer=dealership__pb2.SessionRequest.FromString,
                    response_serializer=dealership__pb2.SessionStatusResponse.SerializeToString,
            ),
            'SaveHumanMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveHumanMessage,
                    request_deserializer=dealership__pb2.MessageRequest.FromString,
                    response_serializer=dealership__pb2.MessageResponse.SerializeToString,
            ),
            'UpdateSessionAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSessionAgent,
                    request_deserializer=dealership__pb2.ClaimRequest.FromString,
                    response_serializer=dealership__pb2.ClaimResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dealership.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dealership.v1.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dealership.v1.ChatService/GetSessionStatus',
            dealership__pb2.SessionRequest.SerializeToString,
            dealership__pb2.SessionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveHumanMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dealership.v1.ChatService/SaveHumanMessage',
            dealership__pb2.MessageRequest.SerializeToString,
            dealership__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSessionAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dealership.v1.ChatService/UpdateSessionAgent',
            dealership__pb2.ClaimRequest.SerializeToString,
            dealership__pb2.ClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModelsList = channel.unary_unary(
                '/dealership.v1.InventoryService/GetModelsList',
                request_serializer=dealership__pb2.ModelsListRequest.SerializeToString,
                response_deserializer=dealership__pb2.ModelsListResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/dealership.v1.InventoryService/CheckAvailability',
                request_serializer=dealership__pb2.AvailabilityRequest.SerializeToString,
                response_deserializer=dealership__pb2.InventoryUnit.FromString,
                _registered_method=True)
        self.UpdateUnitStatus = channel.unary_unary(
                '/dealership.v1.InventoryService/UpdateUnitStatus',
                request_serializer=dealership__pb2.UpdateUnitRequest.SerializeToString,
                response_deserializer=dealership__pb2.UpdateUnitResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetModelsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUnitStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModelsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelsList,
                    request_deserializer=dealership__pb2.ModelsListRequest.FromString,
                    response_serializer=dealership__pb2.ModelsListResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=dealership__pb2.AvailabilityRequest.FromString,
                    response_serializer=dealership__pb2.InventoryUnit.SerializeToString,
            ),
            'UpdateUnitStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUnitStatus,
                    request_deserializer=dealership__pb2.UpdateUnitRequest.FromString,
                    response_serializer=dealership__pb2.UpdateUnitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dealership.v1.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dealership.v1.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetModelsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dealership.v1.InventoryService/GetModelsList',
            dealership__pb2.ModelsListRequest.SerializeToString,
            dealership__pb2.ModelsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dealership.v1.InventoryService/CheckAvailability',
            dealership__pb2.AvailabilityRequest.SerializeToString,
            dealership__pb2.InventoryUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUnitStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dealership.v1.InventoryService/UpdateUnitStatus',
            dealership__pb2.UpdateUnitRequest.SerializeToString,
            dealership__pb2.UpdateUnitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
